/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ukrwebprom (https://sketchfab.com/ukrwebprom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kim-low-poly-character-54a65f4408314f26a442b0e0084a2375
Title: Kim. low poly character
*/
import { useFrame } from '@react-three/fiber'
import React, { useRef } from 'react'
import { useGLTF, useAnimations, useFBX } from '@react-three/drei'

export const P2 = (props) => {
    const model = useFBX("./assets/character/Character2.fbx")

    

    return (
        <>
            <primitive object={model} scale={0.02} position={[props.position[0], props.position[1], props.position[2]]} />

        </>
    )
}

